[package]
name = "piston_graphics"
version = "0.3.0"
authors = ["patevs <ppevans11@gmail.com>"]

[dependencies]
#piston_window = "0.81.0"
piston = "0.39.0"
piston2d-graphics = "0.28.0"
pistoncore-glutin_window = "0.51.0"
piston2d-opengl_graphics = "0.57.0"
